---
title: "ABM"
author: "Astrid Elmann Hansen"
date: '2022-06-11'
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
pacman::p_load(tidyverse)
source("functions/dates.R")
source("functions/invitations.R")
source("functions/generate_matrix.R")
source("functions/matrix_choice.R")
source("functions/update_dyads.R")
```

```{r}
theory <- c("sat", "commit")
```


```{r}
ka <- 2
kp <- 2

N <- 20 # number of agents MUST BE EVEN NUMBER

ticks <- 500 # how many ticks to run

invite_function <- "probinvite" # prob or simple?

intercept <- "random" # random or none?

cl <- "dynamic" # dynamic or static?

cl_timeline <- 10 # number of encounters for calculating cl's (the agents memory)

sims <- 30 # number of sims for each theory
```


```{r}
for (sort in theory){
for (simmer in range(1:sims)){
empty_matrix <- read_csv("functions/empty_matrix.csv", show_col_types = FALSE)

###########
cl_alt_b <- runif(N, min = 1, max = 10) 
cl_alt_b <- as.numeric(rep(cl_alt_b, each=N))

cl_sat_b <- runif(N, min = 1, max = 10)
cl_sat_b <- as.numeric(rep(cl_sat_b, each=N))

inv      <- runif(N, min = 0.1, max = 0.5)
inv      <- as.numeric(rep(inv, each=N))
###########
dyads <- tibble(agent_1 = as.numeric(rep(1:N, each=N)), # create df with dyads and inital values
                agent_2 = as.numeric(rep(seq(1:N),N)),
                sat = 0,
                dep = 0,
                commit = 0,
                tick_no = 0,
                ticks_tog = 0,
                
                cl_alt_b = cl_alt_b,
                cl_sat_b = cl_sat_b,
                cl_alt = 0,
                cl_sat = 0,
                inv = inv,
                
                outcome = 0, # these are cleared after each tick but saved in dyads_his
                out_sat = 0,
                out_dep = 0,
                date = F,
                ac = 0,
                pc = 0,
                jc = 0,
                LOD = 0,
                COI = 0,
                BOD = 0,
                MOD = 0
                )
  
dyads <- dyads %>% filter(agent_1 != agent_2) # Remove dyads with the same agent twice

dyads_his <- dyads
#########

for (tick in 1:ticks){

  hangout <- dates(N = N, dyads = dyads, sort = sort, invite_function = invite_function) # set up date pairs

for (i in 1:nrow(hangout)){ # for every dyad
  
  A <- hangout$A[i] # get the "name" of each agent
  B <- hangout$B[i]
  
  matrix <- generate.matrix(A = A, B = B, matrix = empty_matrix, 
                            dyads = dyads, ka = ka, kp = kp, intercept = intercept) # generate matrix  
  
  A_choice <- own.max(agent = "A", matrix = matrix) # each agent chooses
  B_choice <- own.max(agent = "B", matrix = matrix)

  dyads <- update.dyads(A = A, B = B, A_choice = A_choice, B_choice = B_choice, 
                        matrix = matrix, dyads = dyads, tick = tick, cl = cl, cl_timeline = cl_timeline, sort = sort) # update dyads with new outcomes, tick_tog, sat and dep, AND CL's IF relevant
}

dyads <- dyads %>% mutate(tick_no = tick) # for history dyads
dyads_his <- bind_rows(dyads_his, dyads) # add this tick dyad to dyad_his
dyads <- dyads %>% mutate(outcome = 0, out_dep = 0, out_sat = 0, date = F, ac = 0, pc = 0, jc = 0, LOD = 0, COI = 0, BOD = 0, MOD = 0) # reset
  
print(sprintf("Tick %s of %s, simulation %s of %s, %s", tick, ticks, simmer, sims, sort))

}

filename <- sprintf("logfiles/%s_%s.csv", sort, simmer)
dyads_his  %>% write_csv(filename)
}}
```
