---
title: "viz_dyads"
author: "Astrid Elmann Hansen"
date: '2022-08-03'
output: html_document
---

```{r ignore}
pacman::p_load(tidyverse)
```

```{r ignore}
x <- "tick_no"
path <- c("sat", "dep", "commit", "cl_alt","cl_sat", "ticks_tog", "outcome", "out_sat", "out_dep")
point <- c( "ac", "pc", "jc", "LOD", "COI", "BOD", "MOD")
```


```{r ignore}
# agents to look at
A <- 10
B <- 9
```


```{r ignore}
file_com <- "logfiles/500_ticks_20_agents_commit_probinvite_dynamic_10.csv"

df_com <- read_csv(file_com, # loading file with correct classes
               col_types = list(
                 agent_1 = "f",
                 agent_2 = "f",
                 tick_no = "i",
                 ticks_tog = "i"
               ))

file_sat <- "logfiles/500_ticks_20_agents_sat_probinvite_dynamic_10.csv"

df_sat <- read_csv(file_sat, # loading file_sat with correct classes
               col_types = list(
                 agent_1 = "f",
                 agent_2 = "f",
                 tick_no = "i",
                 ticks_tog = "i"
               ))

```


```{r ignore}
N <- length(unique(df_com$agent_1))
ticks <- max(df_com$tick_no)
```

```{r ignore}
theory <- "Investment"
```

```{r network}
net_com <- df_com %>% filter(date == T) # find info for relevant dyad
color <- "agent_1"

for (y in path){
plot <- net_com %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_path() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}

for (y in point){
plot <- net_com %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_point() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}
```



```{r individual}
agent_A_com <- df_com %>% filter(agent_1 == A) # find info for relevant dyad
color <- "agent_2"

for (y in path){
plot <- agent_A_com %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_path() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}

for (y in point){
plot <- agent_A_com %>%
  filter(date == T) %>% 
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_point() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}
```


##############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################


```{r edit}
theory <- "Interdependence"
```

```{r network}
net_sat <- df_sat %>% filter(date == T) # find info for relevant dyad
color <- "agent_1"

for (y in path){
plot <- net_sat %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_path() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}

for (y in point){
plot <- net_sat %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_point() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}
```

```{r individual}
agent_A_sat <- df_sat %>% filter(agent_1 == A) # find info for relevant dyad
color <- "agent_2"

for (y in path){
plot <- agent_A_sat %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_path() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}

for (y in point){
plot <- agent_A_sat %>%
  filter(date == T) %>% 
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_point() +
  labs(title = theory,
        x ="Time", 
        y = y,
        color = color,
        subtitle = "Line marks a date") +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}
```



```{r both ABMS}
color <- "agent_2"
x <- "tick_no"

path <- c("sat", "commit", "ticks_tog")

A <-  5

agent_A_sat <- df_sat %>% filter(agent_1 == A)
agent_A_com <- df_com %>% filter(agent_1 == A)


for (y in path){
plot <- agent_A_sat %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_path() +
  labs(title = "Interdependence/satisfaction",
        x ="Time", 
        y = y,
        color = color) +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}

for (y in path){
plot <- agent_A_com %>%
  ggplot(aes(x = .data[[x]], y = .data[[y]], color = .data[[color]])) +
  geom_path() +
  labs(title = "Investment/commit",
        x ="Time", 
        y = y,
        color = color) +
  theme(plot.subtitle = element_text(color = "grey")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
print(plot)
}

```



```{r}

sat_1 <- read_csv("logfiles/sat_1.csv", col_types = list(agent_1 = "f",agent_2 = "f",tick_no = "i",ticks_tog = "i"))
sat_2 <- read_csv("logfiles/sat_2.csv", col_types = list(agent_1 = "f",agent_2 = "f",tick_no = "i",ticks_tog = "i"))
com_1 <- read_csv("logfiles/commit_1.csv", col_types = list(agent_1 = "f",agent_2 = "f",tick_no = "i",ticks_tog = "i"))
com_2 <- read_csv("logfiles/commit_2.csv", col_types = list(agent_1 = "f",agent_2 = "f",tick_no = "i",ticks_tog = "i"))

sat_1 <- sat_1  %>% filter(tick_no == 100 & ticks_tog < 75) 
sat_2 <- sat_2  %>% filter(tick_no == 100 & ticks_tog < 75) 
com_1 <- com_1  %>% filter(tick_no == 100 & ticks_tog < 75) 
com_2 <- com_2  %>% filter(tick_no == 100 & ticks_tog < 75) 


x <- c("sat", "dep", "commit", "ticks_tog")

for (x in x){
p <- sat_1 %>% 
  ggplot(aes(x = .data[[x]],  fill = agent_1)) +
  geom_histogram() +
  labs(title = "Interdependence/satisfaction - 1")
print(p)

p <- sat_2 %>% 
  ggplot(aes(x = .data[[x]],  fill = agent_1)) +
  geom_histogram() +
  labs(title = "Interdependence/satisfaction - 2")
print(p)

pp <- com_1 %>% 
  ggplot(aes(x = .data[[x]],  fill = agent_1)) +
  geom_histogram() +
  labs(title = "Investment/commit - 1")
print(pp)

pp <- com_2 %>% 
  ggplot(aes(x = .data[[x]],  fill = agent_1)) +
  geom_histogram() +
  labs(title = "Investment/commit - 2")

print(pp)

}

  
```

